# This property tells Spring Boot to trust the X-Forwarded-Proto header from the Cloud Run proxy.
# This is essential for correct handling of HTTPS redirects and links.
server.forward-headers-strategy=framework

spring.cloud.gcp.logging.enabled=true

